// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Merlin1.0D

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image2 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image2, &ui_img_exactmerlinshat_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 68
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 62
    lv_obj_set_x(ui_Image2, 0);
    lv_obj_set_y(ui_Image2, 60);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image2, 400);

    // ui_Image3 = lv_img_create(ui_Screen1);
    // lv_img_set_src(ui_Image3, &ui_img_greenstar_png);
    // lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 22
    // lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 22
    // lv_obj_set_x(ui_Image3, -1);
    // lv_obj_set_y(ui_Image3, -111);
    // lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    // lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    // lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    // lv_img_set_zoom(ui_Image3, 250);


}
